import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:8123/index.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
console.log('scrub dir initial:', await page.locator('#scrub').getAttribute('dir'));
await page.locator('.seg[data-dir="rtl"]').click(); await page.waitForTimeout(150);
console.log('scrub dir after RTL:', await page.locator('#scrub').getAttribute('dir'));
await page.locator('.seg[data-dir="ltr"]').click(); await page.waitForTimeout(150);
console.log('scrub dir after LTR:', await page.locator('#scrub').getAttribute('dir'));
console.log(errors.length?'ERRORS '+errors.join(';'):'NO ERRORS');
await browser.close();
