import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
page.on('console', m => { if (m.type()==='error') errors.push('CONSOLE: '+m.text()); });
await page.goto('http://localhost:8123/index.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
const rows = await page.locator('.chapter-row').count();
const vlen = await page.locator('#videoLength').inputValue();
const starts = await page.$$eval('.ch-start', els => els.map(e=>e.value));
console.log('rows:', rows, 'videoLength:', vlen, 'starts:', JSON.stringify(starts));
await page.locator('#scrub').evaluate(el => { el.value=500; el.dispatchEvent(new Event('input',{bubbles:true})); });
await page.waitForTimeout(200);
console.log('time label at 50%:', (await page.locator('#timeLabel').textContent()).trim());
await page.locator('.preview-card').screenshot({ path: 'C:/tmp/start_length.png' });
await page.locator('.seg[data-mode="equal"]').click();
await page.waitForTimeout(200);
await page.locator('.preview-card').screenshot({ path: 'C:/tmp/start_equal.png' });
console.log(errors.length ? 'ERRORS:\n'+errors.join('\n') : 'NO ERRORS');
await browser.close();
